DOMAIN_ZH2EN = {
    '生物启发式机械设计教育': 'Bio-inspired mechanical design education',
    '基于需求自动危险检测并生成合适的': 'Automated hazard detection and requirements generation',
    '电子电路设计': 'Electronic circuit design',
    '家具&工业设计': 'Furniture & industrial design',
    '金融服务设计': 'Financial service design',
    '岩土智能制造': 'Geotechnical intelligent manufacturing',
    '健康服务设计': 'Health service design',
    '概念设计': 'Conceptual design',
    '生产线中的智能解决方案和设备': 'Smart solutions & devices in production line',
    '农业灌溉': 'Agricultural irrigation',
    '可视化设计': 'Visualization design',
    '感官迁移设计': 'Somaesthetic design',
    '定制化创新服务设计': 'Customized innovative service design',
    '网站设计': 'Website design',
    '专利设计': 'Patent design',
    '建筑案件诉讼': 'Construction litigation',
    '快速转移使用的知识': 'Rapid knowledge transfer',
    '图形设计': 'Graphic design',
    '插画设计': 'Illustration design',
    '创意写作服务': 'Creative writing service',
    '计算机教育': 'Computer education',
    '生物启发式机械设计': 'Bio-inspired mechanical design',
    '工业设计': 'Industrial design',
    '产品设计': 'Product design',
    '小众工艺': 'Niche craft',
    '教育以及对知识的理解': 'Education & knowledge understanding',
    '视觉传达设计': 'Visual communication design',
    '新闻传达形式扩展': 'News communication extension',
    '跨学科科研': 'Interdisciplinary research',
    '可穿戴产品': 'Wearable product',
    'CAD工具开发': 'CAD tool development',
    '医学服务设计': 'Medical service design',
    '科学教育': 'Science education',
    '同理心催生设计': 'Empathy-driven design',
    '物理教育': 'Physics education',
}